[tool.poetry]
name = "seevooplay"
version = "0.1.0"
description = ""
authors = ["Matthew Newton <matthewn@mahnamahna.net>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.2.4"
django-model-utils = "^4.1.1"
Pillow = "^8.2.0"
django-richtextfield = "^1.6.1"

[tool.poetry.dev-dependencies]
django-extensions = "^3.1.3"
django-debugtools = "^1.8"
Werkzeug = "^2.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
