[tool.poetry]
name = "seevooplay"
version = "1.0.3"
description = "Seevooplay is a Django app for online invitations and RSVPs."
authors = ["Matthew Newton <matthewn@mahnamahna.net>"]
readme = "README.md"
homepage = "https://github.com/matthewn/seevooplay"
repository = "https://github.com/matthewn/seevooplay"
keywords = ["django"]
license = "GPL-3.0-only"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.2.4"
django-model-utils = "^4.1.1"
django-richtextfield = "^1.6.1"
Pillow = "^9.1.0"

[tool.poetry.dev-dependencies]
django-extensions = "^3.1.3"
django-debugtools = "^1.8"
Werkzeug = "^2.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
