# Generated by Django 3.2.4 on 2021-06-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seevooplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'replies'},
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.CharField(max_length=64),
        ),
    ]
