# Generated by Django 6.0.2 on 2026-02-16 22:45

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seevooplay", "0004_swap_pk_to_integer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="legacy_uuid",
            field=models.UUIDField(
                blank=True, editable=False, null=True, verbose_name="legacy UUID"
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="short_uuid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                editable=False,
                length=16,
                max_length=16,
                prefix="",
                unique=True,
                verbose_name="short UUID",
            ),
        ),
    ]
