# Generated by Django 3.2.4 on 2021-06-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seevooplay', '0004_auto_20210606_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='comment',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='reply',
            name='extra_guests',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='status',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('M', 'Maybe')], max_length=1),
        ),
    ]
