# Generated by Django 3.2.4 on 2021-06-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seevooplay', '0005_auto_20210606_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='raw_guests',
            field=models.TextField(blank=True),
        ),
    ]
