# Generated by Django 6.0.2 on 2026-04-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seevooplay", "0006_reply_invitation_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="invitees",
            field=models.TextField(
                blank=True,
                help_text='Enter a list of email addresses separated by commas or new lines.<br>You can put full names before email addresses, and we\'ll try to figure the whole mess out.<br>Quotes and angle brackets will be ignored. Example input:<pre>    prince@example.org, madonna@example.org</pre><pre>    "Rip Torn" &lt;rip_torn@example.org&gt;</pre><pre>    Tim Berners Lee tim@example.org</pre>',
            ),
        ),
    ]
