# Generated by Django 3.2.4 on 2021-06-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seevooplay', '0006_event_raw_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='event_images/'),
        ),
    ]
