# Generated by Django 3.2.4 on 2021-06-09 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seevooplay', '0007_auto_20210608_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ('name',)},
        ),
    ]
