# Generated by Django 3.2.4 on 2021-06-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seevooplay', '0009_rename_raw_guests_event_invitees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invitees',
            field=models.TextField(blank=True, help_text='Enter invitees, one per line. Quotes and angle brackets will be ignored. Valid examples:<br>prince@example.org<br>Prince <prince@example.org><br>"Prince Nelson" prince@example.org<br>Prince Rogers Nelson prince@example.org'),
        ),
    ]
