# Generated by Django 3.2.4 on 2021-06-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seevooplay', '0017_alter_event_invitees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invitees',
            field=models.TextField(blank=True, help_text='Enter invitees, one per line. Quotes and angle brackets will be ignored. Valid examples:<pre>    prince@example.org</pre><pre>    Prince &lt;prince@example.org&gt;</pre><pre>    "Prince Nelson" prince@example.org</pre><pre>    Prince Rogers Nelson prince@example.org</pre><b><i>New invitees will be immediately emailed!</b></i>'),
        ),
    ]
