# Generated by Django 3.2.4 on 2021-06-10 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seevooplay', '0022_alter_event_guests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reply',
            new_name='GuestStatus',
        ),
    ]
