# Generated by Django 3.2.4 on 2021-06-10 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seevooplay', '0023_rename_reply_gueststatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='guests',
        ),
        migrations.DeleteModel(
            name='GuestStatus',
        ),
    ]
