# Generated by Django 3.2.4 on 2021-06-10 05:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seevooplay', '0024_auto_20210609_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('M', 'Maybe')], max_length=1)),
                ('extra_guests', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=512)),
                ('has_viewed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seevooplay.event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seevooplay.guest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(blank=True, through='seevooplay.GuestStatus', to='seevooplay.Guest', verbose_name='Invited guests'),
        ),
    ]
