# Generated by Django 3.2.4 on 2021-06-10 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seevooplay', '0025_auto_20210609_2234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuestStatus',
            new_name='Reply',
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'Replies'},
        ),
    ]
