# Generated by Django 3.2.5 on 2021-08-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seevooplay', '0027_alter_event_invitees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ('guest',), 'verbose_name_plural': 'Replies'},
        ),
        migrations.AlterField(
            model_name='event',
            name='invitees',
            field=models.TextField(blank=True, help_text='\n            Enter a list of email addresses separated by commas or new lines.\n            <br>You can put full names before email addresses, and we\'ll try to\n            figure the whole mess out.\n            <br>Quotes and angle brackets will be ignored. Example input:\n            <pre>    prince@example.org, madonna@example.org</pre>\n            <pre>    "Rip Torn" &lt;rip_torn@example.org&gt;</pre>\n            <pre>    Tim Berners Lee tim@example.org</pre>\n            <big><b><i>New invitees will be immediately emailed!</b></i></big>\n        '),
        ),
    ]
