# Generated by Django 3.2.5 on 2021-08-06 05:20

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('seevooplay', '0028_auto_20210801_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='details',
            field=djrichtextfield.models.RichTextField(blank=True),
        ),
    ]
