# Generated by Django 3.2.5 on 2021-08-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seevooplay', '0029_alter_event_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='host',
            new_name='host1_name',
        ),
        migrations.AddField(
            model_name='event',
            name='host1_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='host2_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='host2_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
