# Generated by Django 3.2.5 on 2021-08-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seevooplay', '0030_auto_20210806_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host1_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='event',
            name='host1_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='event',
            name='host2_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
