# Generated by Django 3.2.5 on 2021-08-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seevooplay', '0031_auto_20210807_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='extra_guests',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
